### ISSUE TITLE
Losing some data when have bad internet connection

### ISSUE THREAD

**Issue by yampi4ek** [OlegKlimenko/Plamber-Android#76]
In online mode, when opening book details I have next issues:
1)All meta-information(language, rating, etc.) are successfully downloaded but image don't.
2)All information(meta and image) are lost.

**Comment by OlegKlimenko** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Losing some data when have bad internet connection](https://trello.com/c/AiJOBvT0/162-losing-some-data-when-have-bad-internet-connection)
