### ISSUE TITLE
Move book details page to toolbar menu

### ISSUE THREAD

**Issue by lolwner** [OlegKlimenko/Plamber-Android#79]
1. On book click go to reading page directly
2. To see details page user will need to click on menu button in toolbar

![inkedphoto_2018-02-18_22-54-23_li](https://user-images.githubusercontent.com/14183135/36356755-04604f62-14ff-11e8-82c7-f22058b83316.jpg)

**Comment by OlegKlimenko** [comment]
@lolwner For now we decided not to change that... But we will see in future
