### ISSUE TITLE
Avatar does not showing in mobile app

### ISSUE THREAD

**Issue by lolwner** [OlegKlimenko/Plamber-Android#80]
1. Upload new avatar via web site
2. Go to mobile app after several minutes
![inkedphoto_2018-02-18_23-33-39_li](https://user-images.githubusercontent.com/14183135/36357259-401ad8f6-1504-11e8-8559-872c8a3bfebb.jpg)

**Comment by OlegKlimenko** [comment]
@lolwner Thanks, this is pretty strange. We will be testing it.

**Comment by OlegKlimenko** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Avatar does not showing in mobile app](https://trello.com/c/7A4T8SZX/161-avatar-does-not-showing-in-mobile-app)
