### ISSUE TITLE
Change logic for local files refresh

### ISSUE THREAD

**Issue by lolwner** [OlegKlimenko/Plamber-Android#90]
Remove ability to manually refresh list of local files (it's not user friendly) and make refreshing list of files automatically (consider using some kind of local storage to store flag that shows is list of books is changed or not. I dunno I'm a web .net developer not an android dev)

**Comment by OlegKlimenko** [comment]
@lolwner I don't know, but most of the apps has the same "logic" with updating data by pulling your screen to the bottom. But we will discuss it with @andrey9328 and see if we will be doing this issue and if it's an issue in general.
Thanks :)

**Comment by OlegKlimenko** [comment]
@lolwner Fixed. Thanks for change proposal :)
