### ISSUE TITLE
Web version - fast scrolling issue

### ISSUE THREAD

**Issue by lolwner** [OlegKlimenko/Plamber-Android#94]
1. Go to any book
2. Scroll down using browser`s scroll
3. You`ll see empty pages https://prnt.sc/l8xy9n
4. If you try to scroll back to the pages, that just got loaded - https://prnt.sc/l8xx2g
5. If you scroll to the next or previous page and then back - it will load correctly

**Comment by OlegKlimenko** [comment]
Moved to https://github.com/OlegKlimenko/Plamber/issues/174
